-- CreateTable
CREATE TABLE "FormSubmission" (
    "id" SERIAL NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "areaType" TEXT,
    "district" TEXT,
    "taluk" TEXT,
    "hobli" TEXT,
    "village" TEXT,
    "urbanArea" TEXT,
    "surveyNo" TEXT,
    "khataNo" TEXT,
    "acres" TEXT,
    "guntas" TEXT,
    "anna" TEXT,
    "applicantType" TEXT,
    "applicantName" TEXT,
    "address" TEXT,
    "applicantDistrict" TEXT,
    "applicantTaluk" TEXT,
    "pincode" TEXT,
    "mobile" TEXT,
    "email" TEXT,
    "aadhaarNo" TEXT,
    "landOwnerName" TEXT,
    "landOwnerAddress" TEXT,
    "landOwnerDistrict" TEXT,
    "landOwnerTaluk" TEXT,
    "east" TEXT,
    "west" TEXT,
    "north" TEXT,
    "south" TEXT,
    "purpose" TEXT,
    "surveyBoundary" TEXT,
    "govtSite" TEXT,
    "govtSiteDetails" TEXT,
    "consent" TEXT,
    "license" TEXT,
    "fupLocation" BYTEA,
    "fupTreeRights" BYTEA,
    "fupKhataExtract" BYTEA,
    "fupRightCertificate" BYTEA,
    "fupLicenseCertificate" BYTEA,
    "fupGPA" BYTEA,
    "declaration" TEXT,

    CONSTRAINT "FormSubmission_pkey" PRIMARY KEY ("id")
);
